# default settings
# encoding: utf-8

#预设style
preset_styles:
  default:
    color_schema: default
    candidate: default
    font: default
  light:
    color_schema: default
    candidate: default
    font: default
  light_land:
    color_schema: default
    candidate: default_land
    font: default_land
  light_md_sm:
    color_schema: default
    candidate: default_md_sm
    keyboards: [default_md_sm, english_md_sm, number_md_sm, symbols_md_sm]
    font: default_md_sm
  light_sm_md:
    color_schema: default
    candidate: default_sm_md
    keyboards: [default_sm_md, english_sm_md, number_sm_md, symbols_sm_md]
    font: default_sm_md
  light_md_md:
    color_schema: default
    candidate: default_md_md
    keyboards: [default_md_md, english_md_md, number_md_md, symbols_md_md]
    font: default_md_md
  light_md_lg:
    color_schema: default
    candidate: default
    font: default_md_lg
    keyboards: [default_md_lg, english_md_lg, number_md_lg, symbols_md_lg]
  light_lg_sm:
    color_schema: default
    candidate: default
    font: default_lg_sm
    keyboards: [default_lg_sm, english_lg_sm, number_lg_sm, symbols_lg_sm]
  dark:
    color_schema: dark
    candidate: default
    font: default
  dark_land:
    color_schema: dark
    candidate: default_land
    font: default
  dark_md_sm:
    color_schema: default
    candidate: default
    font: default_md_sm
    keyboards: [default_md_sm, english_md_sm, number_md_sm, symbols_md_sm]
  dark_sm_md:
    color_schema: default
    candidate: default_sm_md
    keyboards: [default_sm_md, english_sm_md, number_sm_md, symbols_sm_md]
    font: default_sm_md
  dark_md_md:
    color_schema: default
    candidate: default
    font: default_md_md
    keyboards: [default_md_md, english_md_md, number_md_md, symbols_md_md]
  dark_md_lg:
    color_schema: default
    candidate: default
    font: default_md_lg
    keyboards: [default_md_lg, english_md_lg, number_md_lg, symbols_md_lg]
  dark_lg_sm:
    color_schema: default
    candidate: default
    font: default_lg_sm
    keyboards: [default_lg_sm, english_lg_sm, number_lg_sm, symbols_lg_sm]