preset_menu:
  default_menu:
    menu: { events: [
     eisu_toggle_emoji,
     eisu_toggle_clip_board,
     eisu_toggle_clear_setting,
     function_rime_switcher
    ] }
  symbol_menu:
    menu: { events: [ text_fullperiod_default,
     text_fullquestionmark_default,
     text_fullpoint_default,
     text_halfellipsis_default,
     text_halfbracket_left_default,
     text_halfbracket_default,
     text_fullsemicolon_default,
     text_fulldun_default,
     text_fulltilde_default,
     text_fullcolon_default,
     text_fullsquarebracketleft2_left_default,
     text_fullsquarebracketright2_default,
     text_fullsmile_default,
     text_fullcomma2_default,
     text_halfpoundsign_default,
     text_halfcolon_default,
     "%",
     "-",
     "+",
     "×",
     "=" ] }
  all_menu:
    menu: { events: [
     eisu_toggle_schema_board,
     eisu_toggle_sound_board,
     eisu_toggle_edit_keyboard_board,
     eisu_toggle_common_setting_board,
     eisu_toggle_fuzzy_pinyin,
     eisu_toggle_patch_board,
     eisu_toggle_clip_board,
     eisu_toggle_search_clip_board,
     eisu_toggle_pasteboard_setting_board,
     eisu_toggle_pasteboard_favorite_board,
     eisu_toggle_file_manager,
     eisu_toggle_open_web_browser,
#     eisu_toggle_switch_setting,
#     eisu_toggle_schema_setting,
#     eisu_toggle_phrases_board,
     eisu_toggle_haptics_board,
     eisu_toggle_emoji,
     eisu_toggle_dismiss_keyboard,
#     eisu_toggle_dismiss_menu,
#     eisu_toggle_switcher,
#     eisu_toggle_system_info_board,
#     eisu_toggle_user_feedback,
     function_keyboard_clearAll,
     function_keyboard_undo,
     function_keyboard_clearLeft,
     function_keyboard_clearRight,
     function_keyboard_redo,
     function_keyboard_selectAll,
     function_keyboard_cut,
     function_keyboard_copy,
     function_keyboard_paste,
     function_keyboard_newline,
     function_rime_switcher,
     function_rime_deploy,
     function_rime_clear,
     function_common_open_host
    ] }