# default settings
# encoding: utf-8

#style，preset_styles，preset_font，preset_candidates，preset_color_schemas，preset_keyboards 下的default键名是个公共的配置，没有填的话都从default里面取。
style:
  default:
    light: light #竖屏
    light_land: light_land #横屏
    dark: dark #竖屏
    dark_land: dark_land #横屏
    keyboards: [default, english, number, symbols] #键盘配置：自动键盘、字母、数字、符号
    keyboards_land: [default_land, english, number_land, symbols_land] #横屏
  hmos:
    light: light #竖屏
    dark: dark #竖屏
    light_md_sm: light_md_sm #竖屏
    light_sm_md: light_sm_md #横屏
    light_md_md: light_md_md #横屏
    light_land: light_land #横屏
    light_md_lg: light_md_lg #横屏
    light_lg_sm: light_lg_sm #大竖屏
    dark_land: dark_land #横屏
    dark_md_sm: dark_md_sm #竖屏
    dark_sm_md: dark_sm_md #竖屏
    dark_md_md: dark_md_md #竖屏
    dark_md_lg: dark_md_lg #竖屏
    dark_lg_sm: dark_lg_sm #竖屏
    keyboards: [default, english, number, symbols] #键盘配置：自动键盘、字母、数字、符号
    keyboards_land: [default_land, english, number_land, symbols_land] #横屏
    keyboards_md_sm: [default_md_sm, english_md_sm, number_md_sm, symbols_md_sm]
    keyboards_sm_md: [default_sm_md, english_sm_md, number_sm_md, symbols_sm_md]
    keyboards_md_md: [default_md_md, english_md_md, number_md_md, symbols_md_md]
    keyboards_md_lg: [default_md_lg, english_md_lg, number_md_lg, symbols_md_lg]
    keyboards_lg_sm: [default_lg_sm, english_lg_sm, number_lg_sm, symbols_lg_sm]
  iPadOS:
    light: default
    dark: default
  macOS:
    light: default
    dark: default